### ISSUE TITLE
Fail properly if log folder doesn't exist

### ISSUE THREAD

**Issue by jbalbes** [Expium/jira-item-form#6]
Currently, if the folder that is set to contain log files doesn't exist, no item is created in JIRA, but success is reported back to the user.

**Comment by kylecordes** [comment]
The bug report is accurate, but the solution hinted at goes the wrong direction. Rather, the actual fix is: make it so that only complete success is reported as success. If anything it all goes wrong, report failure. Do not do this by "whack a mole" of each kind of thing that can go wrong, but rather by globally only reporting success if nothing went wrong.

**Comment by jbalbes** [comment]
Fixed as of 0.0.11
